version: '3'

services:
  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #     - 8080:8080
  backend:
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./Backend:/app
    command: nodemon -L index.ts
  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_DATABASE=itm-db
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - '80:80'
    volumes:
      - './Frontend:/app'
      
volumes:
  mysql_data:
